package Bibliophiler::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Bibliophiler::Schema',
    connect_info => 'dbi:SQLite:db/bibliophiler.db' ,
);

=head1 NAME

Bibliophiler::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Bibliophiler>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Bibliophiler::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

John SJ Anderson

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
